### ISSUE TITLE
Bump php version support to 5.6

### ISSUE THREAD

**Issue by jonnybarnes** [microformats/php-mf2#104]
Neither 5.4 or 5.5 are receiving security fixes anymore, they’ve been EOL-ed.

See https://secure.php.net/supported-versions.php

**Comment by voxpelli** [comment]
See #101, I'm +1 on increasing it, but it causes problems with eg. some people's WordPress blogs so it was decided to support older ones for now.

**Comment by dshanske** [comment]
I think you are asking the wrong question. What feature do you need that isn't supported in the earlier versions?

**Comment by gRegorLove** [comment]
I'm -0.

We only bumped the Composer requirement from 5.3 to 5.4 a couple months ago with the latest release, and that was primarily for parse_url() fixes. Since the lib works fine on 5.4+, I don't see a strong reason to require higher at this point.

**Comment by aaronpk** [comment]
Agreed with the others. I don't see a reason to bump the requirement to 5.6 as long as it works in 5.4, since there are still active (mostly WordPress) sites running 5.4 and 5.5. WordPress does recommend PHP 5.6 but sadly there are still plenty of hosts that haven't upgraded yet. When this chart shows less 5.4 and 5.5 installations we can bump the requirement https://wordpress.org/about/stats/

**Comment by jonnybarnes** [comment]
5.2 and 5.3 have a depressingly large share :(

**Comment by gRegorLove** [comment]
Re-opening. WordPress 5.2 now requires PHP 5.6.20 ([announced 2019-04-01](https://wordpress.org/news/2019/04/minimum-php-version-update/)). We're pretty sure this was the only reason we kept PHP 5.4 support for so long, so will probably update minimum version to 5.6 with the next release. Any objections?

**Comment by jonnybarnes** [comment]
The wordpress stats page has 12.7% of installs running on php >5.6, I’m all for bumping version support, people running older versions of php will simply get “stuck” on the last version  that supports there setup

**Comment by Ryuno-Ki** [comment]
I mean, I could be wrong, but [PHP 5.6 reached EOL](https://www.php.net/supported-versions.php) last year.
Are you sure, you want to support it?

**Comment by aaronpk** [comment]
We need to support pretty far back in order to support live wordpress sites. Just because a version reaches EOL doesn't mean everyone suddenly upgrades.

**Comment by Ryuno-Ki** [comment]
I know that from the Python world.
However, not guaranteeing support for EOL versions of a runtime can spur motivation to upgrade.
Otherwise you might run into the Python2.7-problem …

**Comment by aaronpk** [comment]
Sure, but this is more about following Wordpress than making our own decision. I seriously doubt this library would be the reason someone would hold off on updating PHP.

**Comment by voxpelli** [comment]
Not possible to release a new major and backport any important changes to the version the WordPress plugin uses?

**Comment by aaronpk** [comment]
Possible? sure. Anyone want to volunteer to do that? 😂

**Comment by dshanske** [comment]
Can I ask again what newer features you want to incorporate? Version should be bumped for that reason. Even though PHP versions hit EOL, that isn't an issue for the library.
