### ISSUE TITLE
Correcting tags in content

### ISSUE THREAD

**Issue by swentel** [microformats/php-mf2#222]
Coming from https://github.com/aaronpk/XRay/issues/102

It looks like mf2 corrects the HTML when there's a missing closing tag of a tag, which messes up the content.

Payload available on the other issue.

To reproduce: paste the payload in http://pin13.net/mf2/ you should get 3 items, instead you'll have two and you will see that there is a closing tag for the first html->content property.

**Comment by sknebel** [comment]
Issue is quite unclear, but when I copy your example HTML in a browser, it cuts the page at the `<script>` tag.  What *exactly* do you think php-mf2 is "correcting" wrongly?

**Comment by swentel** [comment]
Updated the summary with steps to reproduce.

**Comment by sknebel** [comment]
In my browser, the script tag takes over the rest of the page if I copy your example code into a html file, and it does not show 3 posts.
I do agree that the php-mf2 output is kind of weird, but to me this looks like broken HTML from the start?

**Comment by swentel** [comment]
> but to me this looks like broken HTML from the start

The original input came from granary which snarfed has fixed, so the source will be fine from that end.

The question then is indeed: should this library try and correct broken input or not. It seems like it does at the moment as there's a closing script tag at the end when parsing. I haven't looked closely what exactly goes on underneath.

It might be good to just document the behavior that 'broken' input will fail in parsing.

**Comment by sknebel** [comment]
It's not so much the parser attempting to "fix" anything as that being the correct result of parsing your HTML document (which it does, using a HTML parser). If you put the HTML in a browser and look at the DOM in devtools, you see the same thing.

**Comment by swentel** [comment]
Talked this through a bit with sknebel on IRC.

This 'problem' is by design, so there shouldn't be anything fixed here.

Sorry for the noise :)

**Comment by sknebel** [comment]
https://chat.indieweb.org/dev/2021-01-12 is the chatlog for reference
