### ISSUE TITLE
Migrating from travis-ci.org due to shutdown

### ISSUE THREAD

**Issue by barnabywalters** [microformats/php-mf2#224]
The project currently has a build status badge from travis-ci.org, which is shutting down. Any opinions about moving to a different platform for CI?

Migrating to a free plan at travis-ci.com is probably the easiest method, and would presumably work with the existing config file.

I’m late to the party but have been playing around with using Github Actions for build tests, and have a good first impression. The main advantage of that would be tighter integration with github and one less account to manage.

**Comment by aaronpk** [comment]
Closing this since you just moved it all over to GitHub actions!

https://github.com/microformats/php-mf2/actions/workflows/main.yml

Thanks!
