### ISSUE TITLE
Non-recognized root class aborts element processing

### ISSUE THREAD

**Issue by jzeneto** [microformats/php-mf2#230]
Hi! I'm trying to implement microformats2 in my website, which uses Tailwind as CSS framework. In that framework, there are classes such as `h-4`, `h-12` etc (specifying `height` CSS property on element).

Problem is: when I try to validate my h-card, the parsing of an element is aborted when those Tailwind classes are present. A small example follows:

```html
<div class="h-card">
  <img class="u-photo w-32 h-32" alt="Jon Doe"
       src="/image.jpg"/>
</div>
```

The `photo` property is not recognized; but if one removes `h-32` class, `photo` is recognized. I tried this example on two different pages: [Barnaby Walters'](https://waterpigs.co.uk/php-mf2/) and [pin13.net](https://pin13.net/mf2/), and the results are the same.

It seems php-mf2 (used on those 2 pages) aborts the processing of an element when it finds a non recognized root class (which, in this case, isn't even a microformats2 class). This is problematic, I think, since HTML classes are not used only by microformats2.

**Comment by kevinmarks** [comment]
The python parser ignores bad h- classes (from a microformats point of view)
http://www.unmung.com/?html=%3Cdiv+class%3D%22h-card%22%3E%0D%0A++%3Cimg+class%3D%22u-photo+w-32+h-32%22+alt%3D%22Jon+Doe%22%0D%0A+++++++src%3D%22%2Fimage.jpg%22%2F%3E%0D%0A%3C%2Fdiv%3E&pretty=on

**Comment by barnabywalters** [comment]
In this specific case it should be possible to fix this issue, as the utility classes are not valid mf2 root classnames (i.e. they have a number in). Hopefully tailwind and similar libraries don’t introduce any classes which would clash with mf2 classnames (e.g. `h-not-numbers`) — I wonder if it’d be worth getting in contact with the maintainers and letting them know about the potential issue.

I’ll try to take a look at it over the next few days.

**Comment by barnabywalters** [comment]
I merged a fix, which will be in the next point release. Thanks for bringing this issue to our attention!

**Comment by kevinmarks** [comment]
Are there useful test cases here to add to the cross language test suite?

**Comment by barnabywalters** [comment]
@kevinmarks could be, yes — for example, checking that

```html
<div class="h-card">
  <img class="u-photo w-32 h-32" alt="Jon Doe"
       src="/image.jpg"/>
</div>
```

parses correctly to

```json
{
  "items": [
    {
      "type": [
        "h-card"
      ],
      "properties": {
        "name": [
          "Jon Doe"
        ],
        "photo": [
          "/image.jpg"
        ]
      }
    }
  ],
  "rels": {},
  "rel-urls": {}
}
```

Additionally, tests which ensure valid parsing of property vendor prefixes (which may contain numbers) and property name tail strings (which may not) e.g. `p-vendor123` is invalid, `p-vendor123-my-weird-property` is valid, `p-vendor123-property-1` is not.
